tagFormat: "v${version}"

branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      defaultReleaseRules: true
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
      releaseRules:
        - type: feature
          release: minor
        - type: docs
          scope: docs-*
          release: minor
        - type: docs
          release: false
        - type: data
          release: patch
        - type: ci
          scope: ci-*
          release: patch
        - type: chore
          release: false
        - type: no-release
          release: false

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
      writerOpts:
        commitsSort:
          - subject
          - scope
      presetConfig:
        types:
          - type: feat
            section: "🍕 Features"
          - type: feature
            section: "🍕 Features"
          - type: fix
            section: "🐛 Bug Fixes"
          - type: perf
            section: "🔥 Performance Improvements"
          - type: revert
            section: "⏩ Reverts"
          - type: docs
            section: "📝 Documentation"
          - type: style
            section: "🎨 Styles"
          - type: refactor
            section: "🧑‍💻 Code Refactoring"
          - type: test
            section: "✅ Tests"
          - type: build
            section: "🤖 Build System"
          - type: ci
            section: "🔁 Continuous Integration"

  - - "@semantic-release/changelog"
    - changelogTitle: |
        # 📦 Changelog 
        [![conventional commits](https://img.shields.io/badge/conventional%20commits-1.0.0-yellow.svg)](https://conventionalcommits.org)
        [![semantic versioning](https://img.shields.io/badge/semantic%20versioning-2.0.0-green.svg)](https://semver.org)
        > All notable changes to this project will be documented in this file

  - - "@semantic-release/github"
    - addReleases: bottom
      assets:
        - path: "./dist/**/*.{msi,deb,rpm,AppImage,dmg,sha256sum,bin,exe}"
      successComment: false
      failTitle: false

  - - "@semantic-release/git"
    - assets:
        - LICENSE*
        - CHANGELOG.md
      message: |
        chore(${nextRelease.type}): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
