[project]
name = "humlab-penelope"
version = "0.8.4"
description = "Utilities that simplify enelpeing in Jupyter Lab"
authors = [{ name = "Roger Mähler", email = "roger.mahler@hotmail.com" }]
classifiers = [
    'Operating System :: OS Independent',
    'Topic :: Software Development',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.12',
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "bokeh",
    "ftfy",
    "ipycytoscape",
    "ipydatagrid>=1.1.8,<2.0.0",
    "ipyfilechooser",
    "ipywidgets",
    "jupyter_bokeh",
    "loguru",
    "lxml",
    "more_itertools",
    "msgpack>=1.0.2,<2.0.0",
    "nltk>=3.5,<4.0.0",
    "numpy",
    "openpyxl>=3.0.5,<4.0.0",
    "requests>=2.24.0,<3.0.0",
    "scipy==1.12.0",
    "toml",
    "tqdm",
    "click",
    "smart-open>=6.4",
    "python-dotenv",
    "urllib3",
    "pandas>=2.1.0,<3.0.0",
    "networkx>=3.1,<4.0.0",
    "regex",
]

[project.urls]
Homepage = "https://github.com/humlab/penelope"
Repository = "https://github.com/humlab/penelope"

[project.optional-dependencies]
full = [
    "pyarrow",
    "textacy",
    "spacy==3.7.0",
    "gensim",
    "wordcloud",
    "PyYAML",
]

[project.scripts]
vectorize = "penelope.scripts.dtm.vectorize:main"
vectorize-id = "penelope.scripts.dtm.vectorize_id:main"
tm-predict = "penelope.scripts.tm.predict:click_main"
tm-train-id = "penelope.scripts.tm.train_id:click_main"
tm-train-legacy = "penelope.scripts.tm.train_legacy:click_main"
tm-train = "penelope.scripts.tm.train:click_main"
co-occurrence = "penelope.scripts.co_occurrence:main"
pos-tag = "penelope.scripts.pos_tag:main"

#lite = ["jupyterlite"]

[dependency-groups]
dev = [
    "black",
    "coverage",
    "flake8",
    "flake8-pytest-style",
    "isort",
    "memory-profiler",
    "mypy",
    "pep8-naming",
    "pycodestyle",
    "pyflakes",
    "pyinstrument",
    "pylint",
    "pyright",
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "recommonmark",
    "Sphinx",
    "ruff>=0.0.289",
]


[tool.pyright]
include = ["pyriksprot", "tests"]
exclude = [
    ".git",
    ".vscode",
    "**/__init__.py",
    "**/__pycache__",
    "tmp",
    "data",
    "tests/test_data",
    "tests/output",
]
reportMissingTypeStubs = false
reportUntypedFunctionDecorator = false
reportUntypedClassDecorator = true
reportOptionalSubscript = false
reportOptionalMemberAccess = false
reportOptionalCall = false
reportOptionalIterable = false
reportAssignmentType = false
reportArgumentType = false
reportMissingImports = true
reportUnusedVariable = true
reportUnusedImport = true
reportUndefinedVariable = true
reportUnboundVariable = true
reportIncompatibleMethodOverride = false
reportAttributeAccessIssue = false
pythonVersion = "3.12"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "-rfE",
    # "--no-cov",
    "--durations=0",
    # "-q",
    # "-s",
    #"-n4",
]
log_cli = "false"
testpaths = ["tests"]
norecursedirs = [
    "test_data",
    "output",
    "__pycache__",
    "deprecated",
    "penelope",
    "docs",
    ".git",
    ".github",
    ".vscode",
    "profile-reports",
    "tmp",

]
python_files = "*_test.py"
python_functions = "test_*"

# timeout = 300

[tool.black]
line-length = 120
target-version = ["py312"]
skip-string-normalization = true
exclude = '''
(
  \.git
  | \.pypy_cache
  | \.pytest_cache
  | \.mypy_cache
  | deprecated
  | .venv
)
'''

[tool.isort]
# https://github.com/timothycrosley/isort/wiki/isort-Settings
profile = "black"
line_length = 120
py_version = "auto"
float_to_top = true
src_paths = ["penelope", "tests"]
extra_standard_library = ["__paths__"]


# [tool.taskipy.tasks]
# pytest = "pytest --junitxml=test-results/junit.xml"
# bandit = "bandit -c .bandit.yml -r penelope/"
# black = "black penelope"
# black_ci = "black -check penelope"
# flake8 = "flake8 penelope/ tests/"
# generate_requirements = "uv export --format requirements-txt --output-file requirements.txt"
# pre_safety = "task generate_requirements"
# safety = "safety check  -r requirements.txt"
# isort = "isort -rc penelope"
# isort_ci = "isort -rc -c penelope"
# full = "task pytest && task black && task flake8 && task safety && task bandit && task isort"
# ci = "task pytest && task black_ci && task flake8 && task safety && task bandit && task isort_ci"

[tool.coverage]
# https://github.com/nedbat/coveragepy

[tool.coverage.run]
source = ["penelope"]
branch = true
omit = [
    "**/__init__.py",
    "tests/*",
    "interfaces.py",
    "interface.py",
    "penelope/notebook/*",
    "*_gui.py",
]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
show_missing = true
sort = "Name"

[tool.ruff]

line-length = 140
target-version = "py312"
exclude = [
    "__init__.py",
    "test_data",
    "output",
    "__pycache__",
    "deprecated",
    "penelope",
    "docs",
    ".git",
    ".github",
    ".vscode",
    "profile-reports",
    "tmp",
]
ignore = ["E501", "E722", "E731"]
[build-system]
requires = ["setuptools>=62.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["**/*"]

[tool.setuptools.packages.find]
include = ["penelope*"]